export const MESSAGE_CONTENT_MAX_LENGTH = 4000;

export const CONVERSATION_ERROR_CODES = {
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CONVERSATION_FORBIDDEN: 'CONVERSATION_FORBIDDEN',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  INVALID_MESSAGE_PAYLOAD: 'INVALID_MESSAGE_PAYLOAD',
  INVALID_CONVERSATION_PAYLOAD: 'INVALID_CONVERSATION_PAYLOAD',
  /** Scaffold placeholder until Milestone B2/B3 implement the handler. */
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED'
} as const;

export type ConversationErrorCode =
  (typeof CONVERSATION_ERROR_CODES)[keyof typeof CONVERSATION_ERROR_CODES];
