export const COMPANY_ERROR_CODES = {
  COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
  COMPANY_NOT_PUBLIC: 'COMPANY_NOT_PUBLIC',
  COMPANY_PROFILE_FORBIDDEN: 'COMPANY_PROFILE_FORBIDDEN',
  INVALID_PROFILE_PAYLOAD: 'INVALID_PROFILE_PAYLOAD'
} as const;

export type CompanyErrorCode = (typeof COMPANY_ERROR_CODES)[keyof typeof COMPANY_ERROR_CODES];
