export const STUDENT_ERROR_CODES = {
  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
  STUDENT_PROFILE_FORBIDDEN: 'STUDENT_PROFILE_FORBIDDEN',
  INVALID_PROFILE_PAYLOAD: 'INVALID_PROFILE_PAYLOAD'
} as const;

export type StudentErrorCode = (typeof STUDENT_ERROR_CODES)[keyof typeof STUDENT_ERROR_CODES];
